server:
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.zyuer.imagecloud.mybatis.entity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/imagecloud?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
mybatis-plus:
  type-aliases-package: com.zyuer.imagecloud.domain.pojo
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    cache-enabled: false #开启二级缓存
    map-underscore-to-camel-case: false #下划线转驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql日志
  global-config:
    db-config:
      id-type: assign_id  #主键id由雪花算法生成
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
      update-strategy: not_null # 只更新分空字段

knife4j:
  enable: true
  openapi:
    title: ImageCloud接口文档
    description: ImageCloud接口文档
    email : 3229587344@qq.com
    concat: zyuer
    url: https://github.com/Zyuery
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.zyuer.imagecloud.controller
cos:
  client:
    host: https://zyuerbucket-1330881518.cos.ap-nanjing.myqcloud.com

    region: ap-nanjing
    bucket: zyuerbucket-1330881518
